module.exports = {

	sim : {

		type : [
			'A simulation game',
			'A sim game',
			'A management game',
			'A god game',
			'A tycoon game',
			'A board game',
			'A card game',
		],

		action : [
			'buy',
			'sell',
			'trade',
			'farm',
			'',
			'buy and sell',
			'deal in',
			'harvest',
			'collect',
			'gather',
			'look after',
			'hoard',
			'organize',
		],

		resource : [
			'plants',
			'trees',
			'animals',
			'people',
			'workers',
			'employees',
			'citizens',
			'slaves',
			'gems',
			'gold',
			'crystals',
			'resources',
			'mana',
			'water',
			'power',
			'influence',
			'sheep',
			'timber',
			'ore',
			'souls',
			'monsters',
		],

		control : [
			'conquer',
			'manage',
			'control',
			'run',
			'command',
			'build',
			'expand',
			'exploit',
			'create',
			'oversee',
			'supervise',
			'govern',
			'dominate',
		],

		environment : [
			'hospital',
			'theme park',
			'dungeon',
			'empire',
			'island',
			'space station',
			'moon base',
			'railroad',
			'house',
			'town',
			'city',
			'country',
			'world'
		],

		reason : [
			'until time runs out',
			'in timed rounds',
			'and build a town',
			'faster than your opponents',
			'to make money',
			'to survive',
			'to defeat other players',
			'to defeat an ancient evil',
			'to defeat your opponents',
			'against the clock',
			'forever',
			'online',
			'against friends',
			'with friends',
		],

		templates : [
			'{{#with sim}} {{$ type}} where you {{$ action}} {{$ resource}} to {{$ control}} {{$ environment article=true}} {{/with}}',
			'{{#with sim}} {{$ type}} where you {{$ action}} {{$ resource}} and {{$ action}} {{$ resource}} to {{$ control}} {{$ environment article=true}} {{/with}}',
			'{{#with sim}} {{$ type}} where you {{$ action}} {{$ resource}} {{$ reason}} {{/with}}',
			'{{#with sim}} {{$ type}} where you {{$ action}} {{$ resource}} and {{$ action}} {{$ resource}} {{$ reason}} {{/with}}',
		]
	},

	action : {

		type : [
			'An on-rails shooter',
			'An FPS',
			'A first person game',
			'A tactical shooter',
			'A cover based shooter',
			'A top down shooter',
			'A shoot em up',
			'A squad based shooter',
			'A survival horror game',
			'A cooperative shooter',
			'A stealth action game',
			'A twin stick shooter',
		],

		attack : [
			'shoot',
			'shoot at',
			'intimidate',
			'kick',
			'punch',
			'assasinate',
			'argue with',
			'set fire to',
			'scream at',
			'torture',
			'chase',
			'punish',
			'hunt down',
			'crush',
			'battle',
			'chop up',
			'explode',
			'stomp on',
			'beat down',
			'destroy',
			'take down',
			'melt the insides of',
			'ransack the homes of',
			'mercilessly slaughter',
			'go on a genocidal killing spree against',
			'devour the souls of',
		],

		enemies : [
			'nazis',
			'zombies',
			'zombie nazis',
			'goblins',
			'dragons',
			'ghosts',
			'vikings',
			'gangsters',
			'drug dealers',
			'robots',
			'pirates',
			'evil corporations',
			'mutated creatures',
			'rabid animals',
			'nightmare creatures from beyond our universe',
			'possessed townsfolk',
			'rogue government agents',
			'insurgents',
			'hillbillys',
			'devil worshippers'
		],

		modifier : [
			'in the face',
			'for money',
			'with customizable weapons',
			'using the power of your mind',
			'with shurikens',
			'with swords',
			'with machine guns',
			'with a bazooka',
			'with grenades',
			'with a magical sword',
			'with explosive charges',
			'with nuclear weapons',
			'with a tank',
			'from the shadows',
			'with your bare hands',
			'with magical powers',
			'with an experimental physics manipulation weapon',
			'using vehicles'
		],

		extra : [
			'and eat the corpses',
			'and get cash for each kill',
			'and you are invincible',
			'and you are invisible',
			'and your friend betrays you at the end',
			'and you can rewind time',
			'and you can slow down time',
			'and you can control gravity',
			'but you cannot jump',
			'but it turns out you were the bad guy the whole time',
			'but it is all a dream',
			'but it is all a simulation',
			'but you die in one hit',
		],

		templates : [
			'{{#with action}} {{$ type}} where you {{$ attack}} {{$ enemies}} {{$ modifier}} {{/with}}',
			'{{#with action}} {{$ type}} where you {{$ attack}} {{$ enemies}} {{$ modifier}} {{$ extra}} {{/with}}',
			'{{#with action}} {{$ type}} where you {{$ attack}} {{$ enemies}} {{$ extra}} {{/with}}',
		]
	},

	weapon : {

		type : [
			'sword',
			'dagger',
			'knife',
			'pistol',
			'machine gun',
			'bazooka',
			'spear',
			'shield',
			'jetpack',
			'crossbow',
			'pair of gloves',
			'helmet',
			'hat',
			'pair of shoes',
			'familiar',
		],

		effect : [
			'are on fire',
			'are remote controlled',
			'explode',
			'bounce off walls',
			'lock on to enemies',
			'turn enemies to stone',
			'absorb enemies health',
			'misfire occasionaly',
		],

		projectiles : [
			'knives',
			'bullets',
			'fireballs',
			'ice shards',
			'energy blasts',
			'lasers',
			'blobs of goop',
			'healing rays',
			'sound waves',
			'rockets',
			'shrink rays',
			'grenades',
			'bees',
			'sharks',
			'telekinetic energy',
		],

		extra : [
			'but has a long cooldown',
			'but you can only use it once per level',
			'but using it costs you health',
			'and has splash damage',
			'and can be upgraded',
			'and has infinite ammo',
			'and has limited ammo',
			'but is useless against some enemies',
			'but has massive recoil'
		],

		ammo : [
			'bullets',
			'health',
			'enemies',
			'rocks',
			'batteries',
		],

		templates : [
			'{{#with weapon}} A game where you have {{$ type article=true}} that {{$ effect singular=true}} {{$ extra}} {{/with}}',
			'{{#with weapon}} A game where you have {{$ type article=true}} that shoots {{$ projectiles}} {{/with}}',
			'{{#with weapon}} A game where you have {{$ type article=true}} that shoots {{$ projectiles}} that {{$ effect}} {{/with}}',
			'{{#with weapon}} A game where you have {{$ type article=true}} that shoots {{$ projectiles}} and uses {{$ ammo}} as ammo {{/with}}',
		]
	},

	character : {

		job : [
			'space marine',
			'soldier',
			'war veteran',
			'cowboy',
			'gangster',
			'scientist',
			'explorer',
			'pilot',
			'pirate',
			'smuggler',
			'robot',
			'mutant',
			'survivor',
			'test subject',
			'sailor',
			'super soldier',
			'shop keeper',
			'doctor',
			'rock star',
			'middle manager',
			'policeman',
			'minimum wage worker',
			'accountant',
			'chef',
			'traffic warden',
			'school teacher',
			'mime',
			'musician',
			'artist'
		],

		description : [
			'rugged',
			'grizzled',
			'psychotic',
			'depressed',
			'angry',
			'genocidal',
			'lost',
			'lonely',
			'young',
			'old',
			'retired',
			'famous',
			'paranoid',
			'starving',
			'desperate'
		],

		loves : [
			'to dance',
			'to sing',
			'to paint',
			'fruit',
			'money',
			'killing things',
			'running',
			'violence',
			'pizza',
			'swimming',
		],

		hates : [
			'social situations',
			'other people',
			'robots',
			'violence',
			'paperwork',
			'silence',
			'daylight',
			'mornings',
			'citrus fruits',
			'getting wet',
			'being cold',
			'hippies',
			'republicans',
		],

		does : [
			'hoards collectables',
			'avoids conflict',
			'misses home',
			'wants to go home',
			'is afraid of the dark',
			'is afraid of cats',
			'has daddy issues',
			'wears vintage clothes',
			'listens to jazz music',
			'plays the guitar'
		],

		templates : [
			'{{#with character}} A game where you play {{$ description article=true}} {{$ job}} who loves {{$ loves}} {{/with}}',
			'{{#with character}} A game where you play {{$ description article=true}} {{$ job}} who hates {{$ hates}} {{/with}}',
			'{{#with character}} A game where you play {{$ description article=true}} {{$ job}} who loves {{$ loves}} but hates {{$ hates}} {{/with}}',
			'{{#with character}} A game where you play {{$ description article=true}} {{$ job}} who loves {{$ loves}} and {{$ does}} {{/with}}',
			'{{#with character}} A game where you play {{$ description article=true}} {{$ job}} who hates {{$ hates}} and {{$ does}} {{/with}}',
		]
	}

};