/**
 * the raw data used to generate game ideas
 */
module.exports = {

	sim : {

		style : [
			'realistic',
			'stylized',
			'historical',
			'text based',
			'fast paced',
			'realtime',
			'turn based',
			'light hearted',
			'complicated',
			'simple',
			'cutthroat',
			'relaxed',
			'cooperative',
			'multiplayer',
			'massively multiplayer',
			'virtual reality',
			'',
		],

		type : [
			'simulation game',
			'sim game',
			'management game',
			'god game',
			'4X game',
			'tycoon game',
			'strategy game',
			'board game',
		],

		action : [
			'buy',
			'sell',
			'amass',
			'muster',
			'trade',
			'farm',
			'deal in',
			'harvest',
			'collect',
			'gather',
			'look after',
			'hoard',
			'organize',
			'contest',
			'fight over',
			'round up',
			'accumulate',
			'grow',
			'group',
			'chase',
			'hunt',
			'store',
			'hide',
			'tend',
		],

		resource : [
			'plants',
			'trees',
			'animals',
			'people',
			'workers',
			'employees',
			'citizens',
			'slaves',
			'gems',
			'gold',
			'crystals',
			'coins',
			'resources',
			'tokens',
			'mana',
			'water',
			'food',
			'power',
			'influence',
			'sheep',
			'timber',
			'components',
			'machinery',
			'books',
			'knowledge',
			'data',
			'secrets',
			'supplies',
			'nutrients',
			'organs',
			'bonds',
			'stocks',
			'ingredients',
			'ore',
			'drugs',
			'metals',
			'fuel',
			'souls',
			'experiences',
			'monsters',
			'herbs',
			'spices',
			'magic',
		],

		control : [
			'conquer',
			'influence',
			'manage',
			'control',
			'run',
			'command',
			'build',
			'expand',
			'exploit',
			'create',
			'oversee',
			'supervise',
			'govern',
			'dominate',
			'administrate',
		],

		environment : [
			'hospital',
			'theme park',
			'dungeon',
			'tower',
			'zoo',
			'farm',
			'civilization',
			'society',
			'gang',
			'business',
			'company',
			'empire',
			'kingdom',
			'island',
			'territory',
			'forest',
			'space station',
			'moon base',
			'railroad',
			'house',
			'household',
			'government',
			'camp',
			'village',
			'settlement',
			'town',
			'city',
			'country',
			'planet',
			'galaxy',
			'restaurant',
		],

		reason : [
			'until time runs out',
			'in timed rounds',
			'in short bursts',
			'in phases',
			'faster than your opponents',
			'to make money',
			'to survive',
			'to defeat other players',
			'to win 3 rounds',
			'to defeat your opponents',
			'against the clock',
			'forever',
			'online',
			'against friends',
			'with friends',
			'with strangers',
		],

		templates : [
			'{{$ sim.style article=true}} {{$ sim.type}} where you {{$ sim.action}} {{$ sim.resource}} to {{$ sim.control}} {{$ sim.environment article=true}}',
			'{{$ sim.style article=true}} {{$ sim.type}} where you {{$ sim.action}} {{$ sim.resource}} and {{$ sim.action skip=50}} {{$ sim.resource}} to {{$ sim.control}} {{$ sim.environment article=true}}',
			'{{$ sim.style article=true}} {{$ sim.type}} where you {{$ sim.action}} {{$ sim.resource}} {{$ sim.reason}}',
			'{{$ sim.style article=true}} {{$ sim.type}} where you {{$ sim.action}} {{$ sim.resource}} and {{$ sim.action skip=50}} {{$ sim.resource}} {{$ sim.reason}}',
		]
	},

	action : {

		prefix : [
			'multiplayer',
			'massively multiplayer',
			'co-op',
			'cooperative',
			'online',
			'on-rails',
			'tactical',
			'cover based',
			'squad based',
			'turn based',
			'twin stick',
			'top down',
			'first person',
			'third person',
			'virtual reality',
			'',
		],

		type : [
			'shooter',
			'shoot em up',
			'survival horror game',
			'stealth action game',
			'beat em-up',
			'hack n slash',
			'platformer',
			'roguelike',
		],

		attack : [
			'shoot',
			'shoot at',
			'intimidate',
			'kick',
			'punch',
			'savage',
			'violate',
			'abuse',
			'target',
			'assasinate',
			'argue with',
			'set fire to',
			'scream at',
			'torture',
			'chase',
			'punish',
			'hunt down',
			'crush',
			'eradicate',
			'sabotage',
			'wipe out',
			'annihilate',
			'lay waste to',
			'exterminate',
			'butcher',
			'snuff out',
			'erase',
			'maim',
			'hunt',
			'battle',
			'chop up',
			'explode',
			'stomp on',
			'beat',
			'pummel',
			'beat down',
			'destroy',
			'take down',
			'mince',
			'masticate',
			'disfigure',
			'maul',
			'massacre',
			'poke fun at',
			'evade',
			'hide from',
			'observe',
			'spy on',
			'infiltrate',
			'melt the insides of',
			'ransack the homes of',
			'mercilessly slaughter',
			'devour the souls of',
		],

		enemy_type : [
			'cyborg',
			'robot',
			'mutated',
			'mutant',
			'radioactive',
			'evil',
			'misunderstood',
			'scary',
			'rotting',
			'shadowy',
			'mysterious',
			'space',
			'cyber',
			'rabid',
			'escaped',
			'angry',
			'rampaging',
			'out of control',
			'frenzied',
			'diseased',
			'infected',
			'rogue',
			'zombie',
			'possessed',
			'sinister',
			'evolved',
		],

		enemies : [
			'nazis',
			'zombies',
			'dragons',
			'bugs',
			'insects',
			'dinosaurs',
			'yetis',
			'orcs',
			'goblins',
			'constructs',
			'AIs',
			'monkeys',
			'sharks',
			'aliens',
			'rats',
			'bats',
			'samurais',
			'ninjas',
			'pirates',
			'terrorists',
			'wasps',
			'golems',
			'elementals',
			'fairies',
			'lizards',
			'lizardmen',
			'spiders',
			'spies',
			'government agents',
			'skeletons',
			'ghosts',
			'vampires',
			'werewolves',
			'shapeshifters',
			'birds',
			'cats',
			'dogs',
			'fish',
			'soldiers',
			'vikings',
			'yokels',
			'townsfolk',
			'scientists',
			'gangsters',
			'prisoners',
			'drug dealers',
			'robots',
			'demons',
			'devils',
			'ghouls',
			'illusions',
			'cultists',
			'horrors',
			'blobs of ooze',
			'animals',
			'nightmare creatures from beyond our universe',
			'villagers',
			'insurgents',
			'hillbillies',
			'devil worshippers',
			'reporters',
			'bugbears',
			'satyrs',
			'centaurs',
			'ogres',
			'immortals',
			'sirens',
			'basilisks',
			'evil spirits',
			'undead',
			'hydras',
		],

		modifier : [
			'in the face',
			'repeatedly',
			'from above',
			'from below',
			'from behind',
			'for fame',
			'for money',
			'for fun',
			'with customizable weapons',
			'using the power of your mind',
			'with shurikens',
			'with swords',
			'with machine guns',
			'with guns',
			'with a bazooka',
			'with grenades',
			'with a magical sword',
			'with explosive charges',
			'with nuclear weapons',
			'with a tank',
			'in a plane',
			'from space',
			'without being seen',
			'in silence',
			'from the shadows',
			'with your bare hands',
			'with magical powers',
			'using stealth',
			'with an experimental weapon',
			'using vehicles',
			'using lasers',
			'using only a ballpoint pen',
		],

		extra : [
			'and eat the corpses',
			'and loot the corpses',
			'and consume the remains',
			'and get points for each kill',
			'and get cash for each kill',
			'and you are invincible',
			'and you are invisible',
			'and you get betrayed at the end',
			'and you can rewind time',
			'and you can slow down time',
			'and you can control gravity',
			'but you cannot jump',
			'but you cannot heal',
			'but it turns out you were the bad guy the whole time',
			'but it is all a dream',
			'but it is all a simulation',
			'but you die in one hit',
			'',
		],

		templates : [
			'{{$ action.prefix article=true}} {{$ action.type}} where you {{$ action.attack}} {{$ action.enemy_type skip=50}} {{$ action.enemies}} {{$ action.modifier}}',
			'{{$ action.prefix article=true}} {{$ action.type}} where you {{$ action.attack}} {{$ action.enemy_type skip=50}} {{$ action.enemies}} {{$ action.extra skip=50}}',
		]
	},

	setting : {

		in_location : [
			'hospital',
			'garden',
			'house',
			'building',
			'facility',
			'office',
			'street',
			'factory',
			'asylum',
			'car park',
			'mall',
			'city',
			'town',
			'dungeon',
			'village',
			'cave system',
			'cavern',
			'cave',
			'testing facility',
			'combat arena',
			'arena',
			'forest',
			'wood',
			'jungle',
			'desert',
			'field',
			'mine',
			'quarry',
			'sewer',
			'warehouse',
			'war zone',
		],

		on_location : [
			'battlefield',
			'farm',
			'military base',
			'facility',
			'submarine',
			'floating city',
			'underwater city',
			'aeroplane',
			'cruise ship',
			'train',
			'beach',
			'rooftop',
			'mountain',
			'spaceship',
			'moon base',
			'space station',
		],

		description : [
			'desolate',
			'dreary',
			'dangerous',
			'sinister',
			'treacherous',
			'collapsing',
			'spooky',
			'abandoned',
			'flooded',
			'dimly lit',
			'dark',
			'toxic',
			'radioactive',
			'war torn',
			'nondescript',
			'odd looking',
			'strange',
			'mysterious',
			'weird',
			'damp',
			'special',
			'impressive',
			'militarized',
			'once great',
			'destroyed',
			'ruined',
			'haunted',
			'futuristic',
			'steampunk',
			'hostile',
		],

		full : [
			'full of',
			'filled with',
			'covered in',
			'infested with',
			'overrun by',
			'home to',
		],

		occurs : [
			'set',
			'which is set',
			'which takes place',
		],

		how : [
			'explore',
			'traverse',
			'navigate',
			'wander around',
			'travel',
			'go to',
			'must get to the end of',
			'must escape from',
			'must survive in',
			'must clear out',
		],

		templates : [
			'A game {{$ setting.occurs}} in {{$ setting.description article=true}} {{$ setting.in_location}} {{$ setting.full}} {{$ action.enemy_type}} {{$ action.enemies}}',
			'A game {{$ setting.occurs}} on {{$ setting.description article=true}} {{$ setting.on_location}} {{$ setting.full}} {{$ action.enemy_type}} {{$ action.enemies}}',
			'A game where you {{$ setting.how}} {{$ setting.description article=true}} {{$ setting.in_location}} {{$ setting.full}} {{$ action.enemy_type}} {{$ action.enemies}}',
			'A game where you {{$ setting.how}} {{$ setting.description article=true}} {{$ setting.on_location}} {{$ setting.full}} {{$ action.enemy_type}} {{$ action.enemies}}',
		]
	},

	weapon : {

		have : [
			'have',
			'wield',
			'carry',
			'use',
		],

		type : [
			'sword',
			'dagger',
			'knife',
			'machette',
			'shiv',
			'club',
			'hammer',
			'breastplate',
			'pair of glasses',
			'pistol',
			'machine gun',
			'shotgun',
			'rifle',
			'cannon',
			'chainsaw',
			'katana',
			'staff',
			'halberd',
			'bow',
			'crossbow',
			'sniper rifle',
			'assault rifle',
			'gatling gun',
			'bazooka',
			'spear',
			'shield',
			'jetpack',
			'glove',
			'helmet',
			'hat',
			'backpack',
			'ring',
			'boomerang',
			'frisbee',
		],

		effect : [
			'are on fire',
			'are remote controlled',
			'explode',
			'bounce off walls',
			'go through walls',
			'destroy scenery',
			'lock on to enemies',
			'ricochet wildly',
			'turn enemies to stone',
			'burn enemies',
			'melt enemies',
			'entangle enemies',
			'terrify enemies',
			'split in two',
			'blind enemies',
			'glow',
			'glow eerily',
			'sparkle',
			'move randomly',
			'liquify enemies',
			'freeze enemies',
			'stun enemies',
			'absorb enemies health',
		],

		projectiles : [
			'knives',
			'blades',
			'bullets',
			'fireballs',
			'ice shards',
			'energy blasts',
			'blasts',
			'energy beams',
			'beams',
			'particles',
			'jets of foam',
			'jets of water',
			'clouds of steam',
			'small creatures',
			'bits of scenery',
			'pipe bombs',
			'bombs',
			'fireworks',
			'lasers',
			'blobs of goop',
			'healing rays',
			'sound waves',
			'rockets',
			'shrink rays',
			'grenades',
			'land mines',
			'bees',
			'sharks',
			'custard pies',
			'telekinetic blasts',
		],

		extra : [
			'with a long cooldown',
			'with a short cooldown',
			'but needs recharging',
			'but you can only use it once per level',
			'but is discarded after use',
			'but using it costs you health',
			'and deals splash damage',
			'and can be upgraded',
			'and talks to you',
			'and has an annoying AI',
			'and misfires occasionaly',
			'and misfires often',
			'and has infinite ammo',
			'and has scarce ammo',
			'and uses anything as ammo',
			'and has limited ammo',
			'but is useless against some enemies',
			'and is more effective against some enemies',
			'and sometimes gets critical hits',
			'and damages the environment',
			'and looks awesome',
			'and looks stupid',
			'and looks cool',
			'but has massive recoil',
			'but is hard to aim',
			'but has a short range',
			'and has a long range',
		],

		verb : [
			'shoots',
			'deploys',
			'emits',
			'fires',
			'throws',
			'launches',
			'lobs',
		],

		templates : [
			'A game where you {{$ weapon.have}} {{$ weapon.type article=true}} that {{$ weapon.effect singular=true}} {{$ weapon.extra}}',
			'A game where you {{$ weapon.have}} {{$ weapon.type article=true}} that {{$ weapon.verb}} {{$ weapon.projectiles}} {{$ weapon.extra}}',
			'A game where you {{$ weapon.have}} {{$ weapon.type article=true}} that is also {{$ weapon.type article=true}} {{$ weapon.extra}}',
			'A game where you {{$ weapon.have}} {{$ weapon.type article=true}} which is attached to {{$ weapon.type article=true}} {{$ weapon.extra}}',
			'A game where you {{$ weapon.have}} {{$ weapon.type article=true}} that {{$ weapon.verb}} {{$ weapon.projectiles}} that {{$ weapon.effect}}',
		]
	},

	character : {

		verb : [
			'play',
			'control',
			'are',
		],

		job : [
			'space marine',
			'soldier',
			'war veteran',
			'cowboy',
			'gangster',
			'scientist',
			'explorer',
			'pilot',
			'pirate',
			'smuggler',
			'robot',
			'mutant',
			'survivor',
			'test subject',
			'sailor',
			'super soldier',
			'shop keeper',
			'rock star',
			'middle manager',
			'taxi driver',
			'policeman',
			'cop',
			'fireman',
			'doctor',
			'nurse',
			'minimum wage worker',
			'CEO',
			'programmer',
			'accountant',
			'student',
			'teenager',
			'child',
			'baby',
			'housewife',
			'debutante',
			'celebrity',
			'slave',
			'butler',
			'gardener',
			'trucker',
			'postman',
			'chef',
			'traffic warden',
			'school teacher',
			'professor',
			'mime',
			'musician',
			'actor',
			'artist',
			'archeologist',
			'alien',
			'astronaut',
			'hunter',
			'critic',
			'pioneer',
			'daredevil',
			'magician',
			'wizard',
		],

		description : [
			'rugged',
			'grizzled',
			'psychotic',
			'depressed',
			'angry',
			'genocidal',
			'lost',
			'lonely',
			'young',
			'old',
			'drug addled',
			'clean living',
			'born again',
			'retired',
			'famous',
			'paranoid',
			'starving',
			'clumsy',
			'vengeful',
			'manic',
			'repressed',
			'jealous',
			'muscular',
			'skinny',
			'stocky',
			'dilligent',
			'attentive',
			'sketchy',
			'shadowy',
			'mysterious',
			'friendly',
			'hostile',
			'out of place',
			'puzzled',
			'timid',
			'comical',
			'serious',
			'determined',
			'disguised',
			'desperate',
			'illiterate',
			'sickly',
			'mean',
			'miserly',
			'generous',
			'vapid',
			'domineering',
			'loud',
			'quiet',
		],

		thing : [
			'to dance',
			'to sing',
			'to paint',
			'fruit',
			'chocolate',
			'cheese',
			'fast food',
			'pizza',
			'computers',
			'sports',
			'cars',
			'TV',
			'work',
			'money',
			'children',
			'babies',
			'old people',
			'charity',
			'killing things',
			'running',
			'violence',
			'swimming',
			'social situations',
			'to be alone',
			'heights',
			'small spaces',
			'open spaces',
			'the country',
			'the city',
			'other people',
			'robots',
			'art',
			'music',
			'paperwork',
			'silence',
			'daylight',
			'mornings',
			'citrus fruits',
			'getting wet',
			'being cold',
			'hippies',
			'republicans',
			'the monarchy',
		],

		does : [
			'get confused easily',
			'hoards collectables',
			'avoids conflict',
			'seeks conflict',
			'misses home',
			'seeks vengeance',
			'wants company',
			'wants to go home',
			'cant go home',
			'is afraid of the dark',
			'has daddy issues',
			'has mommy issues',
			'wears vintage clothes',
			'listens to jazz music',
			'plays the guitar',
			'has body issues',
			'gets bored easily',
			'lacks confidence',
			'watches too much tv',
			'enjoys life',
			'eats too much',
			'has repressed memories',
			'has anger issues',
			'struggles with maths',
			'longs for a quiet life',
			'has a dark past',
			'might be evil',
			'has no friends',
			'wants to retire',
			'refuses to follow orders',
			'respects authority',
			'ignores orders',
		],

		relationship : [
			'is afraid of',
			'has spent years fighting',
			'is fleeing from',
		],

		templates : [
			'A game where you {{$ character.verb}} {{$ character.description article=true}} {{$ character.job}} who loves {{$ character.thing}}',
			'A game where you {{$ character.verb}} {{$ character.description article=true}} {{$ character.job}} who hates {{$ character.thing}}',
			'A game where you {{$ character.verb}} {{$ character.description article=true}} {{$ character.job}} who loves {{$ character.thing}} but hates {{$ character.thing}}',
			'A game where you {{$ character.verb}} {{$ character.description article=true}} {{$ character.job}} who loves {{$ character.thing}} and hates {{$ character.thing}}',
			'A game where you {{$ character.verb}} {{$ character.description article=true}} {{$ character.job}} who loves {{$ character.thing}} and {{$ character.does}}',
			'A game where you {{$ character.verb}} {{$ character.description article=true}} {{$ character.job}} who hates {{$ character.thing}} and {{$ character.does}}',
			'A game where you {{$ character.verb}} {{$ character.description article=true}} {{$ character.job}} who {{$ character.relationship}} {{$ action.enemies}}',
		]
	},

	adventure : {

		style : [
			'gritty',
			'dark',
			'hyper realistic',
			'stylized',
			'colourful',
			'adult',
			'intense',
			'childish',
			'noir',
			'relaxing',
			'slapstick',
			'historical',
			'contemplative',
			'fast paced',
			'lonely',
			'thought provoking',
			'funny',
			'sarcastic',
			'heart warming',
			'satirical',
			'scary',
			'disturbing',
			'cartoon',
			'cell shaded',
			'light hearted',
			'open world',
			'cooperative',
			'multiplayer',
			'virtual reality',
			'',
		],

		type : [
			'adventure game',
			'story driven game',
			'piece of interactive fiction',
			'RPG',
			'action adventure',
			'role playing game',
			'text adventure',
			'point and click game',
			'action RPG',
		],

		incident : [
			'meet a stranger',
			'discover a dark secret',
			'stumble upon a sinister plot',
			'witness a murder',
			'travel back in time',
			'travel forwards in time',
			'are involved in an accident',
			'are injured',
			'lose everything',
			'lose your memory',
			'lose a loved one',
			'wake up in a strange place',
			'are kidnapped',
			'have a bad day',
			'fall in love',
			'are given an important task',
			'must prove yourself',
		],

		act : [
			'gather a party',
			'gather supplies',
			'craft weapons',
			'explore the area',
			'assemble a team',
			'leave your home town',
			'train your skills',
			'gain special powers',
			'learn new skills',
			'upgrade your equipment',
			'assemble an artifact',
			'piece together clues',
			'gather evidence',
			'perform menial chores',
			'kill monsters',
			'explore mysterious ruins',
			'explore a strange place',
			'experience new emotions',
			'overcome your fear',
			'become a warrior',
			'become the leader',
			'gain respect',
			'are put in charge',
			'collect equipment',
			'learn all you can',
			'escape captivity',
			'go an an epic quest',
			'go on a long journey',
			'visit strange new lands',
			'explore distant lands',
			'struggle against adversity',
			'face terrifying foes',
			'defeat numerous enemies',
			'vanquish determined enemies',
		],

		goal : [
			'gain levels',
			'get the girl',
			'get drunk',
			'get your job back',
			'find true love',
			'discover the truth',
			'redeem yourself',
			'find forgiveness',
			'save the day',
			'become the leader',
			'prove yourself',
			'impress girls',
			'undo your mistakes',
			'reveal the truth',
			'fulfil an ancient prophecy',
			'make up for the past',
			'disover yourself',
			'get rich',
			'look cool',
			'gain fabulous wealth',
			'uncover the secrets of your past',
			'save your family',
			'save a loved one',
			'rescue a loved one',
			'take down a corrupt government',
			'become amazingly wealthy',
			'escape your past',
		],

		templates : [
			'{{$ adventure.type article=true}} where you {{$ adventure.incident}} then {{$ adventure.act}} to {{$ adventure.goal}}',
			'{{$ adventure.type article=true}} where you {{$ adventure.incident}} then {{$ adventure.act}} to {{$ adventure.goal}}',
			'{{$ adventure.style article=true}} {{$ adventure.type }} where you {{$ adventure.incident}} then {{$ adventure.act}} to {{$ adventure.goal}}',
			'{{$ adventure.style article=true}} {{$ adventure.type }} where you {{$ adventure.incident}} then {{$ adventure.act}} to {{$ adventure.goal}}',
		]

	},

	mashup : {

		game : [
			'Minecraft',
			'Mario',
			'Zelda',
			'Halo',
			'Portal',
			'Half Life',
			'Half Life 2',
			'Team Fortress',
			'Doom',
			'Grand Theft Auto',
			'LittleBigPlanet',
			'Wii Fit',
			'Rock Band',
			'Wolfenstein',
			'Quake',
			'Quake 2',
			'Quake 3',
			'Marathon',
			'GTA',
			'Guitar Hero',
			'GoldenEye',
			'Advance Wars',
			'Populous',
			'Black and White',
			'Road Rash',
			'Rez',
			'Lumines',
			'Columns',
			'Nintendogs',
			'Puzzle Quest',
			'Magic the Gathering',
			'Hearthstone',
			'League of Legends',
			'DOTA',
			'Team Fortress 2',
			'Where in the World is Carmen Sandiego?',
			'Resident Evil',
			'Street Fighter',
			'Dark Souls',
			'Starcraft',
			'Ultima Online',
			'World of Warcraft',
			'EVE Online',
			'Everquest',
			'Monster Hunter',
			'The Sims',
			'Dwarf Fortress',
			'Planetside',
			'Rayman',
			'Tetris',
			'Super Monkey Ball',
			'Silent Hill',
			'Skylanders',
			'Ico',
			'Shadow of the Colossus',
			'Katamari Damacy',
			'Animal Crossing',
			'God of War',
			'Diablo',
			'Metal Slug',
			'Banjo Kazooie',
			'Braid',
			'Fez',
			'Prince of Persia',
			'Civilization',
			'Sim City',
			'Bioshock',
			'Shenmue',
			'Uncharted',
			'Tomb Raider',
			'Final Fantasy',
			'Pikmin',
			'Metroid',
			'Mario Kart',
			'Gran Turismo',
			'Mortal Kombat',
			'Devil May Cry',
			'Call of Duty',
			'Angry Birds',
			'Cut the Rope',
			'Fruit Ninja',
			'Farmville',
			'Cookie Clicker',
			'The Oregon Trail',
			'Morrowind',
			'Skyrim',
			'Wing Commander',
			'Elite',
			'Homeworld',
			'Sonic the Hedgehog',
			'Sonic Adventure',
			'Terraria',
			'Tekken',
			'X Wing',
			'Virtua Fighter',
			'Geometry Wars',
			'Mario Party',
			'Brain Age',
			'Second Life',
			'Harvest Moon',
			'Crash Bandicoot',
			'Streets of Rage',
			'Smash Bros',
			'Need for Speed',
			'Breakout',
			'Pong',
			'Battlefield',
			'Assassins Creed',
			'Tony Hawks Pro Skater',
			'Tamagotchi',
			'Command and Conquer',
			'Gauntlet',
			'Metal Gear Solid',
			'Counter Strike',
			'Bejewelled',
			'Pac Man',
			'Unreal Tournament',
			'Far Cry',
			'Crysis',
			'Wii Sports',
			'Hotline Miami',
			'Blast Corps',
			'Toejam and Earl',
			'Dr Mario',
			'Alex Kid',
			'Myst',
			'Carmageddon',
			'Thief',
			'Deus Ex',
			'Snake',
			'Asteroids',
			'QWOP',
			'Tiny Tower',
			'Golden Axe',
		],

		feature : [
			'better',
			'free to play',
			'multiplayer focussed',
			'single player focussed',
			'on mobile',
			'more casual',
			'simpler',
			'more complex',
			'not as good',
			'with permadeath',
			'with crafting',
			'with high scores',
			'more story driven',
			'with a better plot',
			'with social integration',
			'with better graphics',
			'with retro graphics',
			'with more content',
			'shorter',
			'longer',
			'more serious',
			'less serious',
			'darker in tone',
			'lighter in tone',
			'funnier',
			'with a sense of humor',
		],

		compare_look : [
			'with the look of',
			'which looks like',
			'with the graphics of',
		],

		compare_feel : [
			'with elements from',
			'with the gameplay of',
			'which plays like',
			'which controls like',
		],

		templates : [
			'A game like {{$ mashup.game}} mixed with {{$ mashup.game}}, but {{$ mashup.feature}}',
			'A cross between {{$ mashup.game}} and {{$ mashup.game}}, but {{$ mashup.feature}}',
			'A game {{$ mashup.compare_look}} {{$ mashup.game}}, but {{$ mashup.compare_feel}} {{$ mashup.game}}',
			'A game {{$ mashup.compare_feel}} {{$ mashup.game}}, but {{$ mashup.compare_look}} {{$ mashup.game}}',
		]

	},

	indie : {

		description : [
			'open beta',
			'crowd funded',
			'thought provoking',
			'high concept',
			'tongue in cheek',
			'straight faced',
			'critically acclaimed',
			'community made',
			'open source',
			'barely finished',
			'confusing',
			'bug filled',
			'heavily hyped',
			'fan favourite',
			'community favourite',
			'over hyped',
			'misunderstood',
			'post modern',
			'bohemian',
			'hipster',
			'cutting edge',
			'bleeding edge',
			'virtual reality',
		],

		type : [
			'indie platformer',
			'game jam entry',
			'IGF entry',
			'experimental game',
			'tech demo',
			'student project',
			'sandbox game',
			'art house game',
		],

		feature :  [
			'roguelike elements',
			'multiple endings',
			'difficult moral choices',
			'a persistant world',
			'permadeath',
			'crafting',
			'social features',
			'achievements',
			'in app purchases',
			'DLC',
			'episodic content',
			'weekly updates',
			'a developer diary',
			'a twitter account',
			'randomization',
			'amazing graphics',
			'crude graphics',
			'procedural content',
			'user generated content',
			'a high score table',
			'motion controls',
			'touch controls',
			'local multiplayer',
			'a powerful message',
			'an intriguing story',
			'difficult choices',
			'a disturbing subtext',
			'easter eggs',
			'a cloth map',
		],

		issue : [
			'religion',
			'politics',
			'gender',
			'identity',
			'self',
			'existence',
			'love',
			'jealousy',
			'loss',
			'death',
			'birth',
			'loneliness',
			'friendship',
			'hatred',
			'exploration',
			'home',
			'evolution',
			'growth',
			'disease',
			'tyranny',
			'poverty',
			'wealth',
			'control',
			'drugs',
			'sex',
			'addiction',
			'desire',
			'self loathing',
			'illness',
			'humanity',
			'greed',
			'fear',
		],

		restriction : [
			'no text',
			'no UI',
			'a 60 second countdown',
			'only 1 button',
			'programmer art',
			'placeholder art',
			'no sound',
			'only 2 buttons',
			'a limited palette',
			'only 3 colors',
			'8 bit graphics',
			'vector graphics',
			'16 bit graphics',
		],

		dealing : [
			'dealing with issues of',
			'focussed on issues of',
			'dealing with themes of',
		],

		templates : [
			'{{$ indie.description article=true}} {{$ indie.type}} with {{$ indie.feature}} and a theme of {{$ indie.issue}}',
			'{{$ indie.description article=true}} {{$ indie.type}} with {{$ indie.feature}} and a focus on {{$ indie.issue}}',
			'{{$ indie.description article=true}} {{$ indie.type}} with {{$ indie.feature}}, {{$ indie.feature}} and {{$ indie.restriction}}',
			'{{$ indie.description article=true}} {{$ indie.type}} {{$ indie.dealing}} {{$x2 indie.issue}}',
		]
	},

	racing : {

		prefix : [
			'delapidated',
			'shiny new',
			'battle damaged',
			'corporate sponsored',
			'steampunk',
			'futuristic',
			'colorful',
			'cartoony',
			'modified',
			'customizable',
			'fragile',
			'speedy',
			'sluggish',
		],

		type_in : [
			'rally cars',
			'sports cars',
			'F1 cars',
			'karts',
			'SUVs',
			'trucks',
			'hovercraft',
			'row boats',
			'boats',
			'canoes',
			'planes',
			'rockets',
			'shopping carts',
			'spaceships',
			'hovercars',
			'flying saucers',
			'helicopters',
			'hang gliders',
		],

		type_on : [
			'unicycles',
			'segways',
			'horses',
			'jetskis',
			'camels',
			'elephants',
			'dolphins',
			'eagles',
			'motorbikes',
			'motocross bikes',
			'mountain bikes',
			'tricycles',
		],

		extra : [
			'firing weapons',
			'using powerups',
			'hitting boost pads',
			'doing stunts',
			'collecting pickups',
			'placing traps',
			'avoiding traps',
			'dodging hazards',
			'taking shortcuts',
			'against the clock',
			'against your best time',
			'against your friends',
		],
		around : [
			'around',
			'round',
			'through',
			'about',
		],
		control : [
			'race',
			'rush',
			'career',
			'dash',
			'dart',
			'zoom',
			'speed',
			'hurtle',
		],
		templates : [
			'A racing game where you ride {{$ racing.prefix skip=20}} {{$ racing.type_on}} {{$ racing.around}} {{$ setting.description article=true}} {{$ setting.in_location}}',
			'A game where you race {{$ racing.prefix skip=20}} {{$ racing.type_on}} {{$ racing.around}} {{$ setting.description article=true}} {{$ setting.in_location}}',
			'A game where you race {{$ racing.prefix skip=20}} {{$ racing.type_in}} {{$ racing.around}} {{$ setting.description article=true}} {{$ setting.in_location}}',
			'A racing game where you {{$ racing.control}} {{$ racing.around}} {{$ setting.description article=true}} {{$ setting.in_location}} in {{$ racing.prefix skip=20}} {{$ racing.type_in}}',
			'A game where you race {{$ racing.prefix skip=20}} {{$ racing.type_in}} {{$ racing.around}} {{$ setting.description article=true}} {{$ setting.in_location}} {{$ racing.extra}}',
			'A racing game where you {{$ racing.control}} {{$ racing.around}} {{$ setting.description article=true}} {{$ setting.in_location}} in {{$ racing.prefix skip=20}} {{$ racing.type_in}} {{$ racing.extra}}',
		]
	},

	mobile : {
		type : [
			'colorful',
			'cartoony',
			'realistic',
			'stylized',
			'minimalistic',
			'serious',
			'comical',
			'light hearted',
			'complex',
		],
		genre : [
			'arcade game',
			'family game',
			'kids game',
			'strategy game',
			'simulation game',
			'physics game',
			'puzzle game',
			'action game',
			'board game',
			'game',
		],
		input : [
			'drag',
			'press',
			'slide',
			'fling',
			'pinch',
			'slice',
			'draw',
			'touch',
			'swap',
			'control',
			'manipulate',
			'arrange',
			'match',
			'collect',
			'trade',
		],
		subject : [
			'birds',
			'jewels',
			'maps',
			'coins',
			'clans',
			'knights',
			'dragons',
			'words',
			'blocks',
			'poker chips',
			'playing cards',
			'candy',
			'colors',
			'trains',
			'dots',
			'shapes',
			'icons',
			'letters',
			'monsters',
			'aeroplanes',
			'heroes',
			'pigs',
			'cows',
			'goo',
			'plants',
			'zombies',
			'doodles',
			'cookies',
			'farm animals',
			'animals',
			'fruit',
			'vegetables',
			'creatures',
		],
		action : [
			'shake your phone',
			'tilt your phone',
			'wave your phone around',
			'rotate your phone',
			'answer questions',
			'take photos',
			'record videos',
			'geotag locations',
			'check in',
		],
		goal : [
			'to complete levels',
			'to keep playing',
			'to get to the end',
			'to stay alive',
			'to get points',
			'to win',
			'to defeat your opponent',
			'with friends',
			'with strangers',
		],
		extra : [
			'with augmented reality',
			'with in-game currency',
			'with a global high score table',
			'with unlockable content',
			'with unlockable characters',
			'with unlockable levels',
			'with in-app purchases',
			'with cloud saves',
			'with twitter integration',
			'with facebook integration',
			'with instagram integration',
			'with asynchronous multiplayer',
			'with realtime multiplayer',
			'with sharing options',
			'with custom avatars',
			'with custom houses',
			'with custom pets',
			'with no end',
			'with no way to lose',
			'with no way to win',
			'with weekly updates',
			'with monthly updates',
			'with an active community',
			'with user generated content',
		],
		templates : [
			'{{$ mobile.type article=true}} mobile game {{$ mobile.extra}} where you {{$ mobile.input}} {{$ mobile.subject}} {{$ mobile.goal}}',
			'{{$ mobile.type article=true}} mobile game {{$ mobile.extra}} where you {{$ mobile.input}} {{$ mobile.subject}} and {{$ mobile.action}} {{$ mobile.goal}}',
			'{{$ mobile.type article=true}} mobile game where you {{$ mobile.input}} {{$ mobile.subject}} {{$ mobile.goal}}',
			'{{$ mobile.type article=true}} mobile game where you {{$ mobile.input}} {{$ mobile.subject}} and {{$ mobile.action}} {{$ mobile.goal}}',

			'A mobile {{$ mobile.genre}} {{$ mobile.extra}} where you {{$ mobile.input}} {{$ mobile.subject}} {{$ mobile.goal}}',
			'A mobile {{$ mobile.genre}} {{$ mobile.extra}} where you {{$ mobile.input}} {{$ mobile.subject}} and {{$ mobile.action}} {{$ mobile.goal}}',
			'A mobile {{$ mobile.genre}} where you {{$ mobile.input}} {{$ mobile.subject}} {{$ mobile.goal}}',
			'A mobile {{$ mobile.genre}} where you {{$ mobile.input}} {{$ mobile.subject}} and {{$ mobile.action}} {{$ mobile.goal}}',
		]
	},

	boss : {
		when : [
			'the first boss',
			'the last boss',
			'the end boss',
			'the final boss',
			'one of the bosses',
			'an early boss'
		],
		prefix : [
			'giant',
			'huge',
			'large',
			'massive',
			'big',
			'scary',
			'fast',
			'slow',
		],
		type : [
			'ancient',
			'mutated',
			'cyborg',
			'robotic',
			'demonic',
			'flying',
			'drunken',
			'poisoned',
			'rotting',
			'toxic',
			'armored',
			'possessed',
			'radioactive',
			'flaming',
			'diseased',
			'infected',
			'camouflaged',
			'psychotic',
			'supernatural',
			'electrified',
			'super powered',
			'remote controlled',
		],
		creature_which_animate : [
			'crab',
			'dragon',
			'eagle',
			'sea serpent',
			'snake',
			'bear',
			'spider',
			'worm',
			'mech',
			'robot',
		],
		creature_which_inanimate : [
			'computer',
			'AI',
			'brain',
			'tank',
			'helicopter',
			'tree',
			'plant',
			'flower',
		],
		creature_who : [
			'zombie',
			'troll',
			'witch',
			'wizard',
			'necromancer',
			'robot',
			'gunslinger',
			'soldier',
			'ninja',
			'samurai',
			'demon',
			'ghost',
			'statue',
		],
		action : [
			'breathes fire',
			'shoots at you',
			'uses ranged attacks',
			'uses close combat',
			'swipes at you',
			'swings a weapon at you',
			'throws things at you',
			'breaks down walls',
			'climbs the walls',
			'jumps on you',
			'follows you',
			'mirrors your actions',
			'taunts you',
			'mocks you',
			'pins you down',
			'freezes you',
			'burns you',
			'pounces on you',
			'destroys the floor',
			'destroys the room',
			'chases you in circles',
			'hunts you down',
			'fires lasers',
			'shoots rockets',
			'bites you',
			'rushes at you',
			'hides from you',
			'electrocutes you',
			'barges into you',
			'has three attacks',
			'has three modes',
			'has three lives',
			'has loads of health',
			'kills you in one hit',
			/* needs more */
		],
		weakness_thing : [
			'fire',
			'light',
			'ice',
			'water',
			'lava',
			'wind',
			'special moves',
			'falling damage',
			'environmental damage',
			'speed',
			'stealth',
		],
		weakness_animate : [
			'belly',
			'mouth',
			'neck',
			'eyes',
			'hands',
			'face',
			'head',
			'legs',
			'chest',
			'knees',
			'glowing tattoo',
			'weapon',
			'armour',
		],
		weakness_inanimate : [
			'underside',
			'weapons',
			'armour',
			'power supply',
			'back',
			'front',
			'blind spot',
		],
		weakness_when_pre : [
			'just before',
			'just after',
			'at the moment',
			'when',
			'as',
			'while'
		],
		weakness_when_post : [
			'charges up',
			'charges at you',
			'attacks',
			'changes attacks',
			'turns around',
			'taunts you',
			'pauses',
			'powers up',
			'moves',
		],
		gender : [
			'he',
			'she',
		],
		gender_possessive : [
			'his',
			'her',
		],
		templates : [
			'A game where {{$ boss.when}} is {{$ boss.prefix article=true}} {{$ boss.type skip=50}} {{$ boss.creature_which_animate}} which {{$ boss.action}} and its weak spot is its {{$ boss.weakness_animate}}',
			'A game where {{$ boss.when}} is {{$ boss.prefix article=true}} {{$ boss.type skip=50}} {{$ boss.creature_which_inanimate}} which {{$ boss.action}} and its weak spot is its {{$ boss.weakness_inanimate}}',
			'A game where {{$ boss.when}} is {{$ boss.prefix article=true}} {{$ boss.type skip=50}} {{$ boss.creature_who}} who {{$ boss.action}} and has a weak spot on {{$ boss.gender_possessive}} {{$ boss.weakness_animate}}',

			'A game where {{$ boss.when}} is {{$ boss.prefix article=true}} {{$ boss.type skip=50}} {{$ boss.creature_which_animate}} which {{$ boss.action}} and is vulnerable {{$ boss.weakness_when_pre}} it {{$ boss.weakness_when_post}}',
			'A game where {{$ boss.when}} is {{$ boss.prefix article=true}} {{$ boss.type skip=50}} {{$ boss.creature_which_inanimate}} which {{$ boss.action}} and is vulnerable {{$ boss.weakness_when_pre}} it {{$ boss.weakness_when_post}}',
			'A game where {{$ boss.when}} is {{$ boss.prefix article=true}} {{$ boss.type skip=50}} {{$ boss.creature_who}} who {{$ boss.action}} and is vulnerable {{$ boss.weakness_when_pre}} {{$ boss.gender}} {{$ boss.weakness_when_post}}',

			'A game where {{$ boss.when}} is {{$ boss.prefix article=true}} {{$ boss.type skip=50}} {{$ boss.creature_which_animate}} which {{$ boss.action}} and is susceptible to {{$ boss.weakness_thing}}',
			'A game where {{$ boss.when}} is {{$ boss.prefix article=true}} {{$ boss.type skip=50}} {{$ boss.creature_which_inanimate}} which {{$ boss.action}} and is susceptible to {{$ boss.weakness_thing}}',
			'A game where {{$ boss.when}} is {{$ boss.prefix article=true}} {{$ boss.type skip=50}} {{$ boss.creature_who}} who {{$ boss.action}} and is susceptible to {{$ boss.weakness_thing}}',
		]
	},

};
